export const mockProducts = [
  {
    id: "1",
    image: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=400",
    category: "Events & Catering",
    location: "Nairobi, Kenya",
    duration: 240,
    title: "Nyama Choma Catering (20 pax)",
    description: "Traditional Kenyan BBQ catering service for events",
    price: 15000.3,
    currency: "AED",
    rating: 4.5,
    reviewCount: 738,
    isVerified: true,
    merchantLogo: "https://images.unsplash.com/photo-1560179707-f14e90ef3623?w=100",
  },
  {
    id: "2",
    image: "https://images.unsplash.com/photo-1556910096-6f5e72db6803?w=400",
    category: "Professional Services",
    location: "Mombasa, Kenya",
    duration: 120,
    title: "Professional Office Cleaning",
    description: "Thorough office cleaning by trusted professionals",
    price: 5000.0,
    currency: "AED",
    rating: 4.8,
    reviewCount: 245,
    isVerified: false,
  },
  {
    id: "3",
    image: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=400",
    category: "Beauty & Wellness",
    location: "Kampala, Uganda",
    duration: 480,
    title: "Website Redesign Service",
    description: "Complete website redesign with modern UI/UX",
    price: 25000.5,
    currency: "AED",
    rating: 4.2,
    reviewCount: 156,
    isVerified: true,
  },

  // ------------ GENERATED PRODUCTS BELOW --------------

  {
    id: "4",
    image: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=400",
    category: "Home Services",
    location: "Dubai, UAE",
    duration: 180,
    title: "Event Photography Package",
    description: "Professional photoshoot for events and celebrations",
    price: 3200,
    currency: "AED",
    rating: 4.7,
    reviewCount: 412,
    isVerified: true,
  },
  {
    id: "5",
    image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=400",
    category: "Automotive Services",
    location: "Abu Dhabi, UAE",
    duration: 90,
    title: "AC Deep Cleaning",
    description: "Full AC system cleaning for improved performance",
    price: 180,
    currency: "AED",
    rating: 4.3,
    reviewCount: 198,
    isVerified: true,
  },
  {
    id: "6",
    image: "https://images.unsplash.com/photo-1499951360447-b19be8fe80f5?w=400",
    category: "Events & Catering",
    location: "Doha, Qatar",
    duration: 360,
    title: "Brand Identity Design",
    description: "Complete logo and branding design package",
    price: 6000,
    currency: "AED",
    rating: 4.9,
    reviewCount: 602,
    isVerified: true,
  },
  {
    id: "7",
    image: "https://images.unsplash.com/photo-1515378791036-0648a3ef77b2?w=400",
    category: "Professional Services",
    location: "Dubai, UAE",
    duration: 180,
    title: "Laptop Repair & Diagnostics",
    description: "Professional laptop repair service",
    price: 250,
    currency: "AED",
    rating: 4.4,
    reviewCount: 329,
    isVerified: false,
  },
  {
    id: "8",
    image: "https://images.unsplash.com/photo-1598511727144-5e492ec068c4?w=400",
    category: "Beauty & Wellness",
    location: "Sharjah, UAE",
    duration: 300,
    title: "Interior Decoration Service",
    description: "Modern home styling and décor planning",
    price: 11000,
    currency: "AED",
    rating: 4.1,
    reviewCount: 142,
    isVerified: true,
  },
  {
    id: "9",
    image: "https://images.unsplash.com/photo-1581579188871-45ea61f2a0c8?w=400",
    category: "Home Services",
    location: "Dubai, UAE",
    duration: 60,
    title: "Home Spa & Massage",
    description: "Relaxing home spa experience",
    price: 350,
    currency: "AED",
    rating: 4.8,
    reviewCount: 785,
    isVerified: true,
  },
  {
    id: "10",
    image: "https://images.unsplash.com/photo-1498050108023-c5249f4df085?w=400",
    category: "Automotive Services",
    location: "Nairobi, Kenya",
    duration: 720,
    title: "Custom Web App Development",
    description: "Full-stack web application from scratch",
    price: 45000,
    currency: "AED",
    rating: 4.6,
    reviewCount: 204,
    isVerified: true,
  },
  {
    id: "11",
    image: "https://images.unsplash.com/photo-1600891964599-f61ba0e24092?w=400",
    category: "Events & Catering",
    location: "Kigali, Rwanda",
    duration: 180,
    title: "Buffet Catering (50 pax)",
    description: "Delicious buffet with multi-cuisine menu",
    price: 22000,
    currency: "AED",
    rating: 4.0,
    reviewCount: 118,
    isVerified: false,
  },
  {
    id: "12",
    image: "https://images.unsplash.com/photo-1497366216548-37526070297c?w=400",
    category: "Professional Services",
    location: "Doha, Qatar",
    duration: 60,
    title: "Personal Training Session",
    description: "One-on-one home workout session",
    price: 180,
    currency: "AED",
    rating: 4.7,
    reviewCount: 264,
    isVerified: true,
  },
  {
    id: "13",
    image: "https://images.unsplash.com/photo-1503387762-592deb58ef4e?w=400",
    category: "Beauty & Wellness",
    location: "Dubai, UAE",
    duration: 240,
    title: "Local Moving Services",
    description: "Professional movers for homes and offices",
    price: 850,
    currency: "AED",
    rating: 4.5,
    reviewCount: 389,
    isVerified: true,
  },
  {
    id: "14",
    image: "https://images.unsplash.com/photo-1521791055366-0d553872125f?w=400",
    category: "Home Services",
    location: "Abu Dhabi, UAE",
    duration: 90,
    title: "Math Private Tutor",
    description: "One-on-one tutoring for high school students",
    price: 120,
    currency: "AED",
    rating: 4.8,
    reviewCount: 176,
    isVerified: false,
  },
  {
    id: "15",
    image: "https://images.unsplash.com/photo-1504384308090-c894fdcc538d?w=400",
    category: "Automotive Services",
    location: "Dubai, UAE",
    duration: 180,
    title: "Live DJ for Events",
    description: "Professional DJ with full sound setup",
    price: 3500,
    currency: "AED",
    rating: 4.9,
    reviewCount: 502,
    isVerified: true,
  },
  {
    id: "16",
    image: "https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?w=400",
    category: "Events & Catering",
    location: "Nairobi, Kenya",
    duration: 60,
    title: "Home Chef Experience",
    description: "Private chef cooking at your home",
    price: 500,
    currency: "AED",
    rating: 4.4,
    reviewCount: 240,
    isVerified: true,
  },
  {
    id: "17",
    image: "https://images.unsplash.com/photo-1504196606672-aef5c9cefc92?w=400",
    category: "Professional Services",
    location: "Dubai, UAE",
    duration: 120,
    title: "Mobile Car Wash",
    description: "Premium car wash at your home",
    price: 80,
    currency: "AED",
    rating: 4.6,
    reviewCount: 689,
    isVerified: false,
  },
  {
    id: "18",
    image: "https://images.unsplash.com/photo-1560448075-bb4b1cea5f81?w=400",
    category: "Beauty & Wellness",
    location: "Doha, Qatar",
    duration: 45,
    title: "Home Physiotherapy Session",
    description: "Certified physiotherapist for pain relief",
    price: 250,
    currency: "AED",
    rating: 4.9,
    reviewCount: 321,
    isVerified: true,
  },
  {
    id: "19",
    image: "https://images.unsplash.com/photo-1580910051074-7a514d43c59a?w=400",
    category: "Home Services",
    location: "Dubai, UAE",
    duration: 180,
    title: "Nanny Babysitting Service",
    description: "Trusted nanny for home babysitting",
    price: 120,
    currency: "AED",
    rating: 4.3,
    reviewCount: 144,
    isVerified: false,
  },
  {
    id: "20",
    image: "https://images.unsplash.com/photo-1513694203232-719a280e022f?w=400",
    category: "Automotive Services",
    location: "Sharjah, UAE",
    duration: 90,
    title: "Mobile Pet Grooming",
    description: "Professional grooming service at your home",
    price: 200,
    currency: "AED",
    rating: 4.7,
    reviewCount: 402,
    isVerified: true,
  },
];
